### ISSUE TITLE
docutils version > 0.9?

### ISSUE THREAD

**Issue by eggee** [robotframework/QuickStartGuide#14]
Hi, I can't find a version of docutils greater than 0.9 - has anyone else seen this issue and how if so how did you resolve it? Th@nks.

(venv)eggy$ robot QuickStart.rst 
[ ERROR ] Parsing 'QuickStart.rst' failed: Using reStructuredText test data requires having 'docutils' module version 0.9 or newer installed.

**Comment by Tattoo** [comment]
It seems you have not installed [docutils](https://pypi.org/project/docutils/) at all in your virtual environment since they seem to be up to version 0.14

**Comment by eggee** [comment]
worked fine on my Linux box. Must be something with my Mac.

**Comment by Tattoo** [comment]
I just tried it on a Mac, the quick start guide works fine and installing docutils gets the latest version (ie. 0.14) from pypi. 

I recommend to verify you have followed all installation steps, as your error message points to docutils not being installed.

**Comment by eggee** [comment]
Pretty sure it was a Pycharm issue. Once i restarted it, it ran as expected.
