### ISSUE TITLE
No mention is made to the the fact that TABS or four spaces are needed for keywords' arguments

### ISSUE THREAD

**Issue by capitanbatata** [robotframework/QuickStartGuide#3]
I had the following keyword definition:
 
  ``Push button C``

And I kept on getting the ``No keyword with name ... found`` error. It took me a while to figure out that I had to separate the arguments with more spaces (I tried four, and I guess tabs should work as well).

Shouldn't this be mentioned somewhere in the QuickStartGuide? Or do I lack some background that is assumed?

**Comment by pekkaklarck** [comment]
Definitely should be mentioned. Any ideas where and how?

**Comment by capitanbatata** [comment]
Maybe the first time the tabular syntax is introduced: Testcases :: Workflow tests?

Additionally it'd be nice to have a reference where the tabular syntax is described in more detail.
