### ISSUE TITLE
encode error

### ISSUE THREAD

**Issue by Turing-Chu** [robotframework/QuickStartGuide#5]
I have a parameter which is chinese, but it send an error to me:"UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 117: ordinal not in range(128)"

why do you use utf-8?  

I think it is better in python file:
the begining two lines:
    #!/usr/bin/env python
    # -*- coding: utf-8 -*-

**Comment by pekkaklarck** [comment]
Could you clarify how exactly you got that error?

**Comment by Turing-Chu** [comment]
I am testing a web API interface, which use json data and some chinese in it.
But I get an error like this 


UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 65: ordinal not in range(128)



the  affix  contains the robot file


Operationg System:

Linux Turing 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

CentOS release 6.6 (Final)





--

在 2016-01-20 15:39:54，"Pekka Klärck" <notifications@github.com> 写道：


Could you clarify how exactly you got that error?

**Comment by pekkaklarck** [comment]
I see. Such problems have nothing to do with the Quick Start Guide. This issue is thus invalid here.

There's clearly something wrong in your setup, but with the minimal information you provided it is impossible to know what.
